POST http://localhost:3000/api/state
Content-Type: application/json

{
    "data": {
        "process": 0,
        "people": 1,
        "technology": 3,
        "other": 0
    },
    "meta": {
        "color": "",
        "userName": "dsad dasd"
    }
}

###

GET http://localhost:3000/api/state?firstName=das&lastName=das1

###

GET http://localhost:3000/api/state/1?id=1

###

GET http://localhost:3000/api/states

###

GET http://localhost:3000/api/state/1
